### ISSUE TITLE
sequlize 3.9.0 security/injection issue

### ISSUE THREAD

**Issue by williamn** [marin-liovic/restabase#3]
Hi,

Any particular reason why you still require sequalize version 3.9.0?

I got this when I run `npm install`

```
npm WARN deprecated sequelize@3.9.0: security/injection issue with limit/offset fixed in 3.17.0
```

I'll be happy to send a PR to update the version.

Thanks.

**Comment by marin-liovic** [comment]
Hey,
I think it should be fine to use any 3.x version. Feel free to create a PR.

Thanks,
Marin

**Comment by williamn** [comment]
OK I will go to make the PR.

How can I run all the tests in one commannd to make I don't break anything?

Thx

**Comment by marin-liovic** [comment]
You can run all tests with `npm test`. Sadly they do not cover whole functionality yet...

**Comment by williamn** [comment]
OK
